export const contactInputs = [
    {
        type: 'text',
        name: 'fullName',
        placeholder: '\xa0',
        value: null,
        required: true,
        autofocus: false,
        label: 'Full Name',
        errorMsg: 'This field cannot be empty',
    },
    {
        type: 'email',
        name: 'email',
        placeholder: '\xa0',
        value: null,
        required: true,
        autofocus: false,
        label: 'Email',
        errorMsg: 'This field cannot be empty',
    },
    {
        type: 'text',
        name: 'subject',
        placeholder: '\xa0',
        value: null,
        required: true,
        autofocus: false,
        label: 'Subject',
        errorMsg: 'This field cannot be empty',
    },
];