export const projects = [
    {
        'nombre': 'Mis Tareas -Api rest',
        'descripcion': 'API Rest de una aplicacion de tareas por hacer. Permite a un usuario registrarse e iniciar sesion para crear sus Listas de tareas y sus Tareas, guardando los datos en una BD MySQL.',
        'img': 'todo_list_api.png',
        'repositorio': 'https://github.com/JustLearningMX/todo-list',
        'demostracion': 'https://mistareas-api-02abe3439d68.herokuapp.com/swagger-ui/index.html',
        'stack': ['Spring Boot', 'Spring security', 'Java', 'MySQL', 'Swapper UI', 'Heroku'],
        'proyectos': true,
        'alt': 'Mis tareas backend app - Api Rest',
    },
    {
        'nombre': 'Mis Notas -Api rest',
        'descripcion': 'API Rest de una aplicacion de notas que gestiona el CRUD de la información de la BD mediante endpoints que se consumen desde el frontend. Hace uso de tags para filtrar notas.',
        'img': 'Notes_Api.png',
        'repositorio': 'https://github.com/ElianaPranzetti/githubJustLearningMX-ensolvers-challenge/tree/master/backend',
        'demostracion': 'https://notes-app-api-1d668731c17b.herokuapp.com/swagger-ui/index.html',
        'stack': ['Spring Boot', 'Java', 'MySQL', 'Swapper UI', 'Heroku'],
        'proyectos': true,
        'alt': 'My notes backend app - Api Rest',
    },
    {
        'nombre': 'My Notes',
        'descripcion': 'Frontend de la aplicacion de notas que ejecuta un CRUD de la información consumiendo los datos mediantes los endpoints de su propio backend. Hace uso de tags para filtrar notas.',
        'img': 'my_notes.png',
        'repositorio': 'https://github.com/JustLearningMX/my-notes',
        'demostracion': 'https://my-notes-one-tau.vercel.app/',
        'stack': ['React', 'React Router', 'styled-icons', 'HTML', 'CSS', 'JS'],
        'proyectos': true,
        'alt': 'My notes frontend app - React',
    },
    {
        'nombre': 'Purificadora-api',
        'descripcion': 'API Rest de la aplicación purificadora. Gestiona la información de la BD mediante endpoints que se consumen desde el frontend.',
        'img': 'purificadora-api.png',
        'repositorio': 'https://github.com/JustLearningMX/purificadora_api',
        'demostracion': 'https://purificadora-rio-jordan-api.herokuapp.com/v1/api-docs/',
        'stack': ['MongoDB', 'ExpressJS', 'NodeJS', 'JS'],
        'proyectos': true,
        'alt': 'API Rest de la Purificadora de agua',
    },
    {
        'nombre': 'Purificadora React',
        'descripcion': 'Aplicación web con React que permite llevar el control de compras de botellones por agua por cliente para otorgar un llenado gratis. Actualmente en construcción.',
        'img': 'purificadoraReact.png',
        'repositorio': 'https://github.com/JustLearningMX/purificadorariojordan',
        'demostracion': 'https://purificadorariojordan.vercel.app/',
        'stack': ['HTML', 'CSS', 'JS', 'React', 'Redux', 'React Router'],
        'proyectos': true,
        'alt': 'Purificadora de agua con React',
    },
    {
        'nombre': 'libreriapi',
        'descripcion': 'API Rest de la aplicación flipbook. Gestiona la información de la BD mediante endpoints que se consumen desde el frontend. ',
        'img': 'libreriapi.png',
        'repositorio': 'https://github.com/JustLearningMX/LibreriApi',
        'demostracion': 'https://libreriapi.herokuapp.com/v1/api-docs/',
        'stack': ['MongoDB', 'ExpressJS', 'NodeJS', 'JS'],
        'proyectos': true,
        'alt': 'API Rest de la aplicación para comentar libros',
    },
    {
        'nombre': 'flipbook',
        'descripcion': 'Aplicación web frontend que permite comentar libros. Utiliza React para dibujar las vistas.',
        'img': 'flipbook.png',
        'repositorio': 'https://github.com/JustLearningMX/libreria-1',
        'demostracion': 'https://libreria-bedu.herokuapp.com/',
        'stack': ['HTML', 'CSS', 'JS', 'React'],
        'proyectos': true,
        'alt': 'Aplicación para comentar libros',
    },
    {
        'nombre': 'Juego del ahorcado',
        'descripcion': 'Pequeño juego del ahorcado en donde el usuario debe adivinar una serie de letras de una palabra antes de que se terminen sus oportunidades.',
        'img': 'ahorcado.png',
        'repositorio': 'https://github.com/JustLearningMX/juego-ahorcado',
        'demostracion': 'https://justlearningmx.github.io/juego-ahorcado/',
        'stack': ['HTML', 'CSS', 'JS'],
        'proyectos': true,
        'alt': 'Juego del ahorcado',
    },
    {
        'nombre': 'Purificadora',
        'descripcion': 'Aplicación web basica que permite llevar el control de compras de botellones por agua por cliente para otorgar un llenado gratis. Primera version.',
        'img': 'purificadora.png',
        'repositorio': 'https://github.com/JustLearningMX/purificadora',
        'demostracion': 'https://purificadora-rio-jordan.herokuapp.com/',
        'stack': ['HTML', 'CSS', 'JS'],
        'proyectos': true,
        'alt': 'Purificadora de agua',
    },
    {
        'nombre': 'Schoolwebapp',
        'descripcion': 'Aplicación web que genera un CRUD básico con PHP ye permite a estudiantes y maestros registrarse en el colegio ficticio "Águila".',
        'img': 'colegio.png',
        'repositorio': 'https://github.com/JustLearningMX/schoolwebapp_pw2u2',
        'demostracion': 'https://safe-stream-39211.herokuapp.com/',
        'stack': ['HTML', 'CSS', 'JS', 'PHP', 'MySQL'],
        'proyectos': true,
        'alt': 'Aplicación ficticia de un colegio',
    },
];