export const projects = [
    {
        'nombre': 'Mis Tareas -Spring Boot',
        'descripcion': 'API Rest of a to-do application. It allows a user to register and log in to create their Task Lists and Tasks, saving the data in a MySQL DB.',
        'img': 'todo_list_api.png',
        'repositorio': 'https://github.com/JustLearningMX/todo-list',
        'demostracion': 'https://mistareas-api-02abe3439d68.herokuapp.com/swagger-ui/index.html',
        'stack': ['Spring Boot', 'Spring security', 'Java', 'MySQL', 'Swagger UI', 'Heroku'],
        'proyectos': true,
        'alt': 'Mis Tareas -Spring Boot',
    },
    {
        'nombre': 'Mis Tareas -Angular 14',
        'descripcion': 'To-do application in Angular 15. Allows a user to register and login to create their To-Do Lists and Tasks. It uses the proprietary Rest API.',
        'img': 'todo_list_views.png',
        'repositorio': 'https://github.com/JustLearningMX/todo-list-views',
        'demostracion': 'https://justlearningmx.github.io/todo-list-views/inicio',
        'stack': ['Angular', 'PrimeNG', 'PrimeFlex', 'Github-Actions'],
        'proyectos': true,
        'alt': 'Mis Tareas -Angular',
    },
    {
        'nombre': 'Palomazos -ExpressJS',
        'descripcion': 'API of the Palomazos application that manages the database information in MySQL. This application allows people to register with their email and a password to comment and rate movies.\n' +
            '\n',
        'img': 'palomazos-api-rest.png',
        'repositorio': 'https://github.com/Team21-Fullstack-JS/palomazos-api',
        'demostracion': 'https://palomazos-api-a0bcbaa57f47.herokuapp.com/api/v1/documentation/',
        'stack': ['Javascript', 'NodeJS', 'ExpressJS', 'MySQL', 'Swagger UI', 'PassportJS', 'Heroku'],
        'proyectos': true,
        'alt': 'Palomazos -NodeJS and ExpressJS',
    },
    {
        'nombre': 'Palomazos -React/Vite',
        'descripcion': 'Frontend application that allows you to view, comment, and rate movies. It consumes the API Rest of the Palomazos application.',
        'img': 'palomazos-views.png',
        'repositorio': 'https://github.com/Team21-Fullstack-JS/palomazos',
        'demostracion': 'https://team21-fullstack-js.github.io/palomazos/',
        'stack': ['Javascript', 'React', 'Vite', 'Material UI', 'React Router', 'HTML', 'CSS'],
        'proyectos': true,
        'alt': 'Palomazos -React/Vite',
    },
    {
        'nombre': 'My notes -Spring Boot',
        'descripcion': 'API Rest of a notes application that manages the CRUD of the DB information through endpoints that are consumed from the frontend. It uses tags to filter notes.',
        'img': 'Notes_Api.png',
        'repositorio': 'https://github.com/ElianaPranzetti/githubJustLearningMX-ensolvers-challenge/tree/master/backend',
        'demostracion': 'https://notes-app-api-1d668731c17b.herokuapp.com/swagger-ui/index.html',
        'stack': ['Spring Boot', 'Java', 'MySQL', 'Swapper UI', 'Heroku'],
        'proyectos': true,
        'alt': 'My notes backend app - Api Rest',
    },
    {
        'nombre': 'My Notes -React',
        'descripcion': 'Frontend application that allows you to create, edit, and delete notes. It uses tags to filter notes. It consumes the API Rest of the notes application.',
        'img': 'my_notes.png',
        'repositorio': 'https://github.com/JustLearningMX/my-notes',
        'demostracion': 'https://my-notes-one-tau.vercel.app/',
        'stack': ['React', 'React Router', 'styled-icons', 'HTML', 'CSS', 'JS'],
        'proyectos': true,
        'alt': 'My notes frontend app - React',
    },
    {
        'nombre': 'Foodelivery -Spring Boot',
        'descripcion': 'Web application API that gives restaurants the ability to efficiently display and manage their products. In addition, it offers users the ability to track their orders in real time and in detail.',
        'img': 'food-delivery-api.png',
        'repositorio': 'https://github.com/JustLearningMX/s14-12-m-java--angular/tree/main/BACKEND',
        'demostracion': 'https://foodelivery-d2d7a5204308.herokuapp.com/swagger-ui/index.html',
        'stack': ['Spring Boot', 'Java', 'MySQL', 'Swapper UI', 'Heroku'],
        'proyectos': true,
        'alt': 'Foodelivery Spring Boot - Api Rest',
    },
    {
        'nombre': 'Foodelivery -Angular 17',
        'descripcion': 'Frontend from restaurant management application. It allows users to view the products of the restaurants and place orders and admins to manage all about restaurant. It consumes the API Rest of the application.',
        'img': 'food-delivery-views.png',
        'repositorio': 'https://github.com/JustLearningMX/s14-12-m-java--angular/tree/main/FRONTEND',
        'demostracion': 'https://foodeliveries-7bfb7717acda.herokuapp.com/home',
        'stack': ['Angular', 'Typescript', 'PrimeNG', 'PrimeFlex'],
        'proyectos': true,
        'alt': 'Foodelivery -Angular 17',
    },
    {
        'nombre': 'Purificadora-api',
        'descripcion': 'API Rest de la aplicación purificadora. Gestiona la información de la BD mediante endpoints que se consumen desde el frontend.',
        'img': 'purificadora-api.png',
        'repositorio': 'https://github.com/JustLearningMX/purificadora_api',
        'demostracion': 'https://purificadora-rio-jordan-api.herokuapp.com/v1/api-docs/',
        'stack': ['MongoDB', 'ExpressJS', 'NodeJS', 'JS'],
        'proyectos': true,
        'alt': 'API Rest de la Purificadora de agua',
    },
    {
        'nombre': 'Purificadora React',
        'descripcion': 'Aplicación web con React que permite llevar el control de compras de botellones por agua por cliente para otorgar un llenado gratis. Actualmente en construcción.',
        'img': 'purificadoraReact.png',
        'repositorio': 'https://github.com/JustLearningMX/purificadorariojordan',
        'demostracion': 'https://purificadorariojordan.vercel.app/',
        'stack': ['HTML', 'CSS', 'JS', 'React', 'Redux', 'React Router'],
        'proyectos': true,
        'alt': 'Purificadora de agua con React',
    },
    {
        'nombre': 'libreriapi',
        'descripcion': 'API Rest de la aplicación flipbook. Gestiona la información de la BD mediante endpoints que se consumen desde el frontend. ',
        'img': 'libreriapi.png',
        'repositorio': 'https://github.com/JustLearningMX/LibreriApi',
        'demostracion': 'https://libreriapi.herokuapp.com/v1/api-docs/',
        'stack': ['MongoDB', 'ExpressJS', 'NodeJS', 'JS'],
        'proyectos': true,
        'alt': 'API Rest de la aplicación para comentar libros',
    },
    {
        'nombre': 'flipbook',
        'descripcion': 'Aplicación web frontend que permite comentar libros. Utiliza React para dibujar las vistas.',
        'img': 'flipbook.png',
        'repositorio': 'https://github.com/JustLearningMX/libreria-1',
        'demostracion': 'https://libreria-bedu.herokuapp.com/',
        'stack': ['HTML', 'CSS', 'JS', 'React'],
        'proyectos': true,
        'alt': 'Aplicación para comentar libros',
    },
    {
        'nombre': 'Juego del ahorcado',
        'descripcion': 'Pequeño juego del ahorcado en donde el usuario debe adivinar una serie de letras de una palabra antes de que se terminen sus oportunidades.',
        'img': 'ahorcado.png',
        'repositorio': 'https://github.com/JustLearningMX/juego-ahorcado',
        'demostracion': 'https://justlearningmx.github.io/juego-ahorcado/',
        'stack': ['HTML', 'CSS', 'JS'],
        'proyectos': true,
        'alt': 'Juego del ahorcado',
    },
    {
        'nombre': 'Purificadora',
        'descripcion': 'Aplicación web basica que permite llevar el control de compras de botellones por agua por cliente para otorgar un llenado gratis. Primera version.',
        'img': 'purificadora.png',
        'repositorio': 'https://github.com/JustLearningMX/purificadora',
        'demostracion': 'https://purificadora-rio-jordan.herokuapp.com/',
        'stack': ['HTML', 'CSS', 'JS'],
        'proyectos': true,
        'alt': 'Purificadora de agua',
    },
    {
        'nombre': 'Schoolwebapp',
        'descripcion': 'Aplicación web que genera un CRUD básico con PHP ye permite a estudiantes y maestros registrarse en el colegio ficticio "Águila".',
        'img': 'colegio.png',
        'repositorio': 'https://github.com/JustLearningMX/schoolwebapp_pw2u2',
        'demostracion': 'https://safe-stream-39211.herokuapp.com/',
        'stack': ['HTML', 'CSS', 'JS', 'PHP', 'MySQL'],
        'proyectos': true,
        'alt': 'Aplicación ficticia de un colegio',
    },
];